### PR TITLE
docs: fixes anchor links

### PR DESCRIPTION
**Pull request by prosazhin**
This PR fixes anchor links in docs. [Preview](https://deploy-preview-1516--tetragon.netlify.app/docs/getting-started/try-tetragon-linux/#start-tetragon)

### CODE REVIEW

**Review by mtardy — APPROVED** [review]
Looks good, so those are values that will need to be manually edited if we edit the height of the navbar? could you add a comment to explain that :) thanks! checkpatch finds your commit too long, I think it's missing an empty line between the commit title and the sign-off

**Comment by prosazhin** [comment]
@mtardy Yes, that's correct. If the header height changes, then these values need to be adjusted to maintain the same visual quality. Thank you for the feedback. I will leave comments in the code.

**Comment by mtardy** [comment]
Can you squash your commits into the first one?

**Comment by prosazhin** [comment]
@mtardy Done, ready to check

**Comment by mtardy** [comment]
Thanks a lot!

**Pull request merged**
