### PR TITLE
<WIP> For issue#1976 - jobs-app is replaced with Google's online boutique app

### PR DESCRIPTION
**Pull request by rajesamp**
Hi 👋! 

This PR is ". 

Title : to address "TestLabelsDemoApp failures 

This patch fixes this by adding:
I have updated code reference of app - jobs-app to Google's Online Boutique in helm chart & labelsEventChecker which is lightweight and expected to run without failure.

Fixes: #1976

### CODE REVIEW

**Comment by rajesamp** [comment]
Please let me know if any follow up corrections needed for this PR, thanks

**Comment by mtardy** [comment]
> Hello @mtardy - Please let me know if any follow up corrections needed for this PR, thanks

Hey thanks for trying this! You can take a look at this job https://github.com/cilium/tetragon/actions/runs/8120867506?pr=2176 to see what failed, and you can run the e2e tests locally by doing `make e2e-test`. It looks like the app doesn't deploy properly already. I think you'll need to update the labels accordingly as well, not sure they are correct as of now. You can try until `make e2e-test` passes locally.

**Comment by rajesamp** [comment]
Unsuccessful in standing up working version of app in local, using Mac Intel core, Sonoma. Any pointers how to progress will be helpful @mtardy

**Comment by Trung-DV** [comment]
Hi @rajesamp, I have followed the Google microservices-demo to use helm to deploy boutique app manually https://github.com/GoogleCloudPlatform/microservices-demo/tree/main/helm-chart and then use golang code to install it https://github.com/Trung-DV/tetragon/blob/c24e60f5c71e4dc2b7dc4a6fb6a92c639bf1f548/tests/e2e/tests/labels/labels_test.go#L44-L51, seems that #1976 is not simply replace `jobs-app` by `online-boutique`, we have to update `labelsEventChecker` to verify services of online-boutique app. I think we should write a new test labels test for Online Boutique app as well as the labelsEventChecker for it.

**Comment by Trung-DV** [comment]
Dear @rajesamp, @mtardy , I have replaced `jobs-app` by `onlinebuotique` as well as update the labels checker. Please help me to review. 
I rewrite labels checker by compare the current `jobs-app` charts (which found from https://github.com/usrbinkat/pulumi-kubernetes/blob/main/pulumi/src/jobs_app/charts/jobs-app/charts/elasticsearch/templates/statefulset.yaml) and compared to `onlineboutique` from https://github.com/GoogleCloudPlatform/microservices-demo/tree/90b81cca772eb61b8695a638e44b9b2cde70853f/helm-chart/templates, does this is a right approach?

**Comment by mtardy** [comment]
> Dear @rajesamp, @mtardy , I have replaced `jobs-app` by `onlinebuotique` as well as update the labels checker. Please help me to review this PR: [rajesamp#1](https://github.com/rajesamp/tetragon/pull/1)

Can you open a PR against the main repo from your fork?

**Comment by Trung-DV** [comment]
> > Dear @rajesamp, @mtardy , I have replaced `jobs-app` by `onlinebuotique` as well as update the labels checker. Please help me to review this PR: [rajesamp#1](https://github.com/rajesamp/tetragon/pull/1)
> 
> Can you open a PR against the main repo from your fork?

Dear @mtardy,
I have opened PR #2345, can you give me some advises to enhance the labels for Online Boutique in case we need them?

**Comment by lambdanis** [comment]
This PR has been superseded by #2345, so I'm closing it. Thank you @rajesamp

**Pull request closed without merging**
