### PR TITLE
Delete entries from execve_map when pid != tgid

### PR DESCRIPTION
**Pull request by tpapagian**
Signed-off-by: Anastasios Papagiannis <tasos.papagiannnis@gmail.com>

### CODE REVIEW

**Review by olsajiri — APPROVED** [review]

**Comment by jrfastab** [comment]
hmm so how did we get an entry in the map though with a non thread group ID?

**Comment by olsajiri** [comment]
> 

there are places like 
https://github.com/cilium/tetragon/blob/a34d1ffe6650510ed6f060c8b283a10b2bdd690a/bpf/lib/bpf_events.h#L198

and 
https://github.com/cilium/tetragon/blob/a34d1ffe6650510ed6f060c8b283a10b2bdd690a/bpf/lib/bpf_events.h#L152

where we go down through parents.. which I'm actually not sure they need to be group leaders, but we don't check.. also execve tracepoint does not check if the pid is group leader

**Comment by jrfastab** [comment]
I think those should be execve_map_get_noinit()?

**Comment by tpapagian** [comment]
Closing this as we are going to take the fix in https://github.com/cilium/tetragon/pull/370

**Pull request closed without merging**
