### PR TITLE
feat: update label on hero section on main page

### PR DESCRIPTION
**Pull request by annaindistress**
This PR updates label in hero section on home page

### CODE REVIEW

**Review by mtardy — CHANGES_REQUESTED** [review]
Hey, thanks! It seems there is a small issue 
image

feel free to check the preview of your changes on https://deploy-preview-2644--tetragon.netlify.app/.

**Review by mtardy — COMMENTED** [review]
lovely! could you squash your commits into one?

**Review by mtardy — APPROVED** [review]
sure! to me it's fine, let's ask for @xmulligan and @paularah opinions

**Comment by mtardy** [comment]
you miss an empty line between your commit message and signature however, see checkpatch

**Review by xmulligan — APPROVED** [review]

**Pull request merged**
