### PR TITLE
docs: missing space indent

### PR DESCRIPTION
**Pull request by cjtim**
I found some missing indent in document

### CODE REVIEW

**Review by mtardy — CHANGES_REQUESTED** [review]
Hey, welcome to Tetragon! Mmh what makes you think there are missing space indents in these examples? I don't think your fix is correct.

**Comment by cjtim** [comment]
> Hey, welcome to Tetragon! Mmh what makes you think there are missing space indents in these examples? I don't think your fix is correct.

@mtardy 
there are inconsistent space across same document

https://github.com/cilium/tetragon/pull/809/files#diff-cb2007a8853b538bf3423def3ca65bc7a057c3ed57485a3ff360ba50df7ed31cR253-R261

**Review by mtardy — COMMENTED** [review]
Ah yes, you are correct sorry indeed. Have you addressed all of them?

**Comment by cjtim** [comment]
@mtardy I just reviewed it for the third time. look like that's all of it.

**Comment by mtardy** [comment]
> @mtardy I just reviewed it for the third time. look like that's all of it.

Thanks a lot for taking the time, one more nit I'm sorry and it involves git, could you squash your commits into one with a message like "docs: fix indentation inconsistencies across TracingPolicy examples" and [sign with a real email address](https://docs.cilium.io/en/stable/contributing/development/contributing_guide/#developer-s-certificate-of-origin)?

See https://stackoverflow.com/questions/5189560/how-do-i-squash-my-last-n-commits-together and https://docs.pi-hole.net/guides/github/how-to-signoff/ if you need help.

**Comment by cjtim** [comment]
@mtardy fix commit message and signed with a real email

**Comment by mtardy** [comment]
> @mtardy fixed commit message and signed with a real email

Thanks a lot the squash and message are perfect, [the commit](https://github.com/cilium/tetragon/pull/809/commits/28a92ae7b4e85d023fcc5420babe195fe4e09a99) still misses the signed-off line in the message.

**Comment by cjtim** [comment]
@mtardy Oh done please check again. This is my first time :)

**Review by mtardy — APPROVED** [review]
> @mtardy Oh done please check again. This is my first time :)

No worries, now you learned how to squash commits and amend the message to rectify the message and the signature which is _very_ useful. Thanks for your PR.

**Pull request merged**
