### PR TITLE
build: Generate SBOM during image release

### PR DESCRIPTION
**Pull request by michi-covalent**
Add a Software Bill of Materials (SBOM) generated from source code and the image using the Kubernetes bom tool to the Tetragon image during image build.

Signed-off-by: Sandipan Panda <samparksandipan@gmail.com>

### CODE REVIEW

**Comment by michi-covalent** [comment]
this is a copy of https://github.com/cilium/tetragon/pull/559 to test the workflow file changes

**Review by willfindlay — APPROVED** [review]

**Comment by sandipanpanda** [comment]
@michi-covalent, we could fix the issue we were facing with signing the SBOM images for Cilium thanks to André. I have carried forward the fix for Tetragon. Can you please update this PR to see if the Image CI Build checks pass now with the changes?

**Comment by michi-covalent** [comment]
sorry for the delay, where do i need to pull in the change from?

**Comment by sandipanpanda** [comment]
With https://github.com/cilium/tetragon/commit/343e9f94c6eca025307cc5219638102c57c184c2 merged, this is no longer needed and can be closed.

**Pull request closed without merging**
