### PR TITLE
Docs: add a tutorial on how to read Tetragon metrics

### LINKED ISSUE #928: Add documentation/tutorial on how to read Tetragon metrics
From a [discussion on the Cilium Slack](https://cilium.slack.com/archives/C03EV7KJPJ9/p1681438217891409):

Question:
> How can I see the Prometheus metrics generated by Tetragon?

Answer:
> If you run Tetragon with the helm chart, it should be enabled, you can read `cat /var/run/tetragon/tetragon-info.json` for the info but typically it listens on `2112`.
>
> If you run Tetragon standalone you can use: `sudo ./tetragon --bpf-lib ./bpf/objs/ --metrics-server localhost:2112` to start with the metrics server (it's disabled by default)
>
> Then to read the the metrics you can do `curl localhost:2112/metrics`.

### PR DESCRIPTION
**Pull request by YTGhost**
Fixes #928

### CODE REVIEW

**Review by mtardy — COMMENTED** [review]
Hey! Thank you for trying to tackle these issues, but I don't think that's super relevant to just copy-paste my answer from the issue paragraph. This was just supposed to give context to the content of such a tutorial. Was that confusing? It's perfectly ok to not have the whole context and we could discuss what this page could be about on the issue.

**Comment by mtardy** [comment]
@YTGhost do you plan to propose something for this PR or should we close it?

**Comment by YTGhost** [comment]
> @YTGhost do you plan to propose something for this PR or should we close it?

Sorry because I've been busy with a lot of school projects lately and may not have much time here in the near future, so please close this pr.

In addition it seems that @prateek041 is interested in this issue, maybe he can take over the job.

**Comment by mtardy** [comment]
> Sorry because I've been busy with a lot of school projects lately and may not have much time here in the near future, so please close this pr.

really no worries, we do our best! Thanks for trying.

**Pull request closed without merging**
