### PR TITLE
deprecate sensors gRPC API

### PR DESCRIPTION
**Pull request by kkourt**
The gRPC sensors interface is the initial interface for manging collections of bpf programs at run-time. It has been replaced by tracing policies. This PR deprecates the sensor management gRPC calls.

Fixes: https://github.com/cilium/tetragon/issues/1272

CC: @inliquid

### CODE REVIEW

**Review by mtardy — APPROVED** [review]
I think we are okay to deprecate since the TracingPolicy can do everything one should need now. Note that the linter doesn't like that we use (our own) deprecated API, we should add a "ignore".

**Comment by kkourt** [comment]
> I think we are okay to deprecate since the TracingPolicy can do everything one should need now. Note that the linter doesn't like that we use (our own) deprecated API, we should add a "ignore".

Thanks, added an ignore.

**Comment by inliquid** [comment]
Thanks! We moved to TracingPolicy API beforehand so this doesn't affect us.

**Review by olsajiri — APPROVED** [review]
lgtm

**Pull request merged**
