### PR TITLE
Various Dockerfile cleanups

### PR DESCRIPTION
**Pull request by mtardy**

### CODE REVIEW

**Comment by mtardy** [comment]
> Build job will need updating to account for the rename.

It is updated, but the the build job is a `pull_request_target`.

**Comment by mtardy** [comment]
See https://github.com/cilium/tetragon/pull/843/files#diff-bc7d1a70d1cf51591f508724daa5a8e98f987c7a594acd8e40d3fe4b8da9e319R33

**Comment by mtardy** [comment]
Do you want to proceed like usual? Changing to `pull_request` to test the impossible-to-test `pull_request_target`?

**Comment by willfindlay** [comment]
> Do you want to proceed like usual? Changing to pull_request to test the impossible-to-test pull_request_target? 

Yeah let's do a rebase and then let's test with the `pull_request` target.

**Review by willfindlay — APPROVED** [review]

**Comment by mtardy** [comment]
Not all the checks succeed because of the rename of `operator.Dockerfile` to `Dockerfile.operator` but this is expected because the workflow use `pull_request_target` event. [Tests were made adding the `pull_request` target](https://github.com/cilium/tetragon/actions/runs/4618951104/jobs/8167042859?pr=843). Merging this now!

**Pull request merged**
