### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Wholesomebruh**
debugged broken link

### CODE REVIEW

**Comment by mtardy** [comment]
Thanks for the patch! However, it looks like your commit is not signed-off, to improve tracking of who did what, the Tetragon project uses a "sign-off" procedure which you can learn more about in the [Cilium project documentation](https://docs.cilium.io/en/latest/contributing/development/contributing_guide/#developer-s-certificate-of-origin).

Concretely it consists of adding your real name and an email address to your git config and using `git commit -s` to write your commit message. You can use `git commit --amend -s` to add the signature to existing commits.

<details><summary><b>See more details on how to comply with the "sign-off" procedure</b></summary>
<p>

To add your name and email to your git config:
```shell
git config user.email "mail@example.com"
git config user.name "firstname lastname"
```
_Note: add the `--global` flag after `config` to configure this by default for repositories on your host._

Then you can use for new commits:
```shell
git commit -s
```

Or for existing commits on which you want to add the `signed-off-by` statement:
```shell
git commit --amend -s
```

_For more information, see this extract from `git-commit(1)` man page regarding the `-s` flag_:
```
-s, --signoff, --no-signoff
   Add a Signed-off-by trailer by the committer at the end of the commit log
   message. The meaning of a signoff depends on the project to which you're
   committing. For example, it may certify that the committer has the rights to
   submit the work under the project's license or agrees to some contributor
   representation, such as a Developer Certificate of Origin. (See
   http://developercertificate.org for the one used by the Linux kernel and Git
   projects.) Consult the documentation or leadership of the project to which
   you're contributing to understand how the signoffs are used in that project.

   The --no-signoff option can be used to countermand an earlier --signoff
   option on the command line.
```

</p>
</details>

Can you also write your commit message with something like `README: fix tracing policy doc broken link`

**Comment by mtardy** [comment]
Can you squash your 3 commits into one?

**Comment by Wholesomebruh** [comment]
Hi, sorry for the mess, can you please help me with that.

**Comment by mtardy** [comment]
Still we need a real name in the author and signature field.

**Comment by Wholesomebruh** [comment]
What needs to be done for that? My name is "Baibhav" , but I don't have github account with that name.

**Comment by mtardy** [comment]
Please take a look at this again:

Thanks for the patch! However, it looks like your commit is not signed-off, to improve tracking of who did what, the Tetragon project uses a "sign-off" procedure which you can learn more about in the [Cilium project documentation](https://docs.cilium.io/en/latest/contributing/development/contributing_guide/#developer-s-certificate-of-origin).

Concretely it consists of adding your real name and an email address to your git config and using `git commit -s` to write your commit message. You can use `git commit --amend -s` to add the signature to existing commits.

<details><summary><b>See more details on how to comply with the "sign-off" procedure</b></summary>
<p>

To add your name and email to your git config:
```shell
git config user.email "mail@example.com"
git config user.name "firstname lastname"
```
_Note: add the `--global` flag after `config` to configure this by default for repositories on your host._

Then you can use for new commits:
```shell
git commit -s
```

Or for existing commits on which you want to add the `signed-off-by` statement:
```shell
git commit --amend -s
```

_For more information, see this extract from `git-commit(1)` man page regarding the `-s` flag_:
```
-s, --signoff, --no-signoff
   Add a Signed-off-by trailer by the committer at the end of the commit log
   message. The meaning of a signoff depends on the project to which you're
   committing. For example, it may certify that the committer has the rights to
   submit the work under the project's license or agrees to some contributor
   representation, such as a Developer Certificate of Origin. (See
   http://developercertificate.org for the one used by the Linux kernel and Git
   projects.) Consult the documentation or leadership of the project to which
   you're contributing to understand how the signoffs are used in that project.

   The --no-signoff option can be used to countermand an earlier --signoff
   option on the command line.
```

</p>
</details>

**Comment by jrfastab** [comment]
@Wholesomebruh hi! patch looks good just need a real name on the signed off by.  I think to do this open your .gitconfig and change the name to a real name. And then do the `git commit  --ammend -s` and push again and should be good to go.

**Pull request closed without merging**
