### PR TITLE
update github.com/cilium/ebpf

### PR DESCRIPTION
**Pull request by lmb**
Manually update the dependency to preempt a broken automated bump. This is because we removed the LogSize field upstream.

### CODE REVIEW

**Comment by mtardy** [comment]
Ah that explains that https://github.com/cilium/tetragon/pull/2662 with https://github.com/cilium/tetragon/actions/runs/10039047288/job/27742214979?pr=2662#step:8:54

**Comment by lmb** [comment]
Apparently this now depends on https://github.com/cilium/cilium/pull/33961 :see_no_evil:

**Comment by mtardy** [comment]
> Apparently this now depends on [cilium/cilium#33961](https://github.com/cilium/cilium/pull/33961) 🙈

😑 we need to remove that Cilium dep one day or later, it's really annoying

**Comment by lmb** [comment]
Someone mind re-running the failed test for me? I don't think it's related to this PR.

**Review by kkourt — APPROVED** [review]

**Pull request merged**
