### PR TITLE
docs: remove cncf label on homepage

### PR DESCRIPTION
**Pull request by paularah**
Thanks for contributing! Please ensure your pull request adheres to the following guidelines:

- [x] All commits contain a well written commit message and are signed-off (see [Submitting a pull request](https://tetragon.io/docs/contribution-guide/submitting-a-pull-request/)).
- [x] All code is covered by unit and/or end-to-end tests where feasible.
- [x] All generated files are updated if needed (see [Making changes](https://tetragon.io/docs/contribution-guide/making-changes/)).
- [x] Provide a title or release-note blurb suitable for the release notes (see [guidelines](https://tetragon.io/docs/contribution-guide/docs/release-notes/#release-note-blurb-in-pr)).
- [x] Update documentation and write an upgrade note if needed (see [guidelines](https://tetragon.io/docs/contribution-guide/docs/release-notes/#upgrade-notes)).
- [x] Are you a user of Tetragon? Please add yourself to the [Users doc](https://github.com/cilium/cilium/blob/main/USERS.md) in the Cilium repository.

Removes the  CNCF label on the homepage for reasons we've discussed.

### CODE REVIEW

**Comment by xmulligan** [comment]
I think we should keep this, we just also need to mention that Tetragon is a subproject under Cilium like the website said before the update

**Review by xmulligan — CHANGES_REQUESTED** [review]
It should be updated not removed

**Comment by mtardy** [comment]
> for reasons we've discussed

would love to have more context on that discussion 😄

**Review by mtardy — CHANGES_REQUESTED** [review]
Given Bill's comment:

> It should be updated not removed

I don't have more context sorry

**Comment by xmulligan** [comment]
The reasons being that right now it looks like Tetragon is a stand alone CNCF project while it is actually under Cilium which is the overarching CNCF project

**Comment by paularah** [comment]
Yes. A slight redesign from PP would fix this

**Comment by paularah** [comment]
@mtardy PP will handle the update to this. I'll close this if that's fine with you.

**Pull request closed without merging**
