### PR TITLE
Cross-compile arm64 container images

### PR DESCRIPTION
**Pull request by mtardy**
This is part of https://github.com/cilium/tetragon/issues/487.

Very fun fact that I learned today, `tetra` requires CGO because it imports `tetragon/pkg/bpf`. I hope you are laughing now!

### CODE REVIEW

**Comment by mtardy** [comment]
Mmmh @willfindlay, [the workflow is using a `pull_request_target`](https://github.com/cilium/tetragon/pull/816/files#diff-bc7d1a70d1cf51591f508724daa5a8e98f987c7a594acd8e40d3fe4b8da9e319L4) which makes it difficult to test. Should we modify this?

**Comment by chancez** [comment]
@mtardy the way we do this in other projects is to do something like:
```
  push:
    branches:
      - main
      - ft/**
```

Then you have to push a branch to origin (not a fork) and name if `ft/whatever-your-feature-is`.

**Comment by mtardy** [comment]
> @mtardy the way we do this in other projects is to do something like:
> 
> ```
>   push:
>     branches:
>       - main
>       - ft/**
> ```
> 
> Then you have to push a branch to origin (not a fork) (which only maintainers can do) and name it `ft/whatever-your-feature-is`.

We had a little chat with @chancez and it seems that you need to approve the CI run on each PR changes when it comes from a fork. I had this situation this morning and I had to click "Approve to run the CI" after the contributor push new changes, on a little button at the level of the checks on the page. See: https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks#approving-workflow-runs-on-a-pull-request-from-a-public-fork

**Comment by chancez** [comment]
@mtardy I think in both cases, if your PR is from origin, it should have the access required.

**Comment by mtardy** [comment]
[I used the `pull_request` trick to see](https://github.com/cilium/tetragon/pull/816/files#diff-bc7d1a70d1cf51591f508724daa5a8e98f987c7a594acd8e40d3fe4b8da9e319R11-R12). Let see if I'm getting bullied by the SBOM generation again.

**Comment by mtardy** [comment]
btw the workflows thinks I'm pushing as if I was on main because the if statement is a bit wrong:
https://github.com/cilium/tetragon/actions/runs/4440138016/workflow?pr=816#L85-L87

It should be:
```yaml
if: ${{ github.event_name == 'push' }}
```

instead of:
```yaml
if: ${{ github.event_name != 'pull_request_target' }}
```

**Comment by mtardy** [comment]
I just tested this build manually with Docker on amd64 and arm64 and it worked https://quay.io/repository/cilium/tetragon-ci?tab=tags&tag=7b9af7c2e69d3ba611ac4e4e4418155ab7b85c3d 🥳 .

**Review by willfindlay — APPROVED** [review]

**Comment by mtardy** [comment]
I applied the following changes before final push:

```diff
diff --git a/.github/workflows/build-images-ci.yml b/.github/workflows/build-images-ci.yml
index e035d196..4876571d 100644
--- a/.github/workflows/build-images-ci.yml
+++ b/.github/workflows/build-images-ci.yml
@@ -8,8 +8,6 @@ on:
       - reopened
     paths-ignore:
       - 'docs/**'
-  # this is temporary and for test purposes, it has to be removed
-  pull_request:
   push:
     branches:
       - main
@@ -84,7 +82,7 @@ jobs:
 
       # main branch pushes
       - name: CI Build (main)
-        if: ${{ github.event_name != 'pull_request_target' }}
+        if: github.event_name == 'push'
         uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
         id: docker_build_ci_main
         with:
@@ -100,14 +98,14 @@ jobs:
             quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci:latest
 
       - name: Sign Container Image
-        if: ${{ github.event_name != 'pull_request_target' }}
+        if: github.event_name == 'push'
         env:
           COSIGN_EXPERIMENTAL: "true"
         run: |
           cosign sign quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci@${{ steps.docker_build_ci_main.outputs.digest }}
 
       - name: Generate SBOM
-        if: ${{ github.event_name != 'pull_request_target' }}
+        if: github.event_name == 'push'
         shell: bash
         # To-Do: Format SBOM output to JSON after a new version of cosign is released after v1.13.1. Ref: https://github.com/sigstore/cosign/pull/2479
         run: |
@@ -116,12 +114,12 @@ jobs:
           --image=quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci:${{ steps.tag.outputs.tag }}
 
       - name: Attach SBOM to container images
-        if: ${{ github.event_name != 'pull_request_target' }}
+        if: github.event_name == 'push'
         run: |
           cosign attach sbom --sbom sbom_ci_main_${{ matrix.name }}_${{ steps.tag.outputs.tag }}.spdx quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci@${{ steps.docker_build_ci_main.outputs.digest }}
 
       - name: Sign SBOM Image
-        if: ${{ github.event_name != 'pull_request_target' }}
+        if: github.event_name == 'push'
         env:
           COSIGN_EXPERIMENTAL: "true"
         run: |
@@ -131,7 +129,7 @@ jobs:
           cosign sign "quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci@${docker_build_ci_main_sbom_digest}"
 
       - name: CI Image Releases digests (main)
-        if: ${{ github.event_name != 'pull_request_target' }}
+        if: github.event_name == 'push'
         shell: bash
         run: |
           mkdir -p image-digest/
@@ -139,7 +137,7 @@ jobs:
 
       # PR updates
       - name: CI Build (PR)
-        if: ${{ github.event_name == 'pull_request_target' }}
+        if: github.event_name == 'pull_request_target' || github.event_name == 'pull_request'
         uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
         id: docker_build_ci_pr
         with:
@@ -154,14 +152,14 @@ jobs:
             quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci:${{ steps.tag.outputs.tag }}
 
       - name: Sign Container Image
-        if: ${{ github.event_name == 'pull_request_target' }}
+        if: github.event_name == 'pull_request_target' || github.event_name == 'pull_request'
         env:
           COSIGN_EXPERIMENTAL: "true"
         run: |
           cosign sign quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci@${{ steps.docker_build_ci_pr.outputs.digest }}
 
       - name: Generate SBOM
-        if: ${{ github.event_name == 'pull_request_target' }}
+        if: github.event_name == 'pull_request_target' || github.event_name == 'pull_request'
         shell: bash
         # To-Do: Format SBOM output to JSON after a new version of cosign is released after v1.13.1. Ref: https://github.com/sigstore/cosign/pull/2479
         run: |
@@ -170,12 +168,13 @@ jobs:
           --image=quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci:${{ steps.tag.outputs.tag }}
 
       - name: Attach SBOM to container images
-        if: ${{ github.event_name == 'pull_request_target' }}
+        if: github.event_name == 'pull_request_target' || github.event_name == 'pull_request'
         run: |
           cosign attach sbom --sbom sbom_ci_pr_${{ matrix.name }}_${{ steps.tag.outputs.tag }}.spdx quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci@${{ steps.docker_build_ci_pr.outputs.digest }}
 
       - name: Sign SBOM Image
-        if: ${{ github.event_name == 'pull_request_target' }}
+        if: github.event_name == 'pull_request_target' || github.event_name == 'pull_request'
+        run: |
         env:
           COSIGN_EXPERIMENTAL: "true"
         run: |
@@ -185,7 +184,7 @@ jobs:
           cosign sign "quay.io/${{ github.repository_owner }}/${{ matrix.name }}-ci@${docker_build_ci_pr_sbom_digest}"
 
       - name: CI Image Releases digests (PR)
-        if: ${{ github.event_name == 'pull_request_target' }}
+        if: github.event_name == 'pull_request_target' || github.event_name == 'pull_request'
         shell: bash
         run: |
           mkdir -p image-digest/
```

**Review by willfindlay — APPROVED** [review]

**Pull request merged**
