### PR TITLE
tetragon: run Tetragon without access to CRD

### LINKED ISSUE #1880: Run Tetragon without access to CRD
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

In some scenarios we have a limited access to k8s cluster, so that when installing tetragon with `helm` , it fails with getting CRD "tracingpolicies.cilium.io":
изображение

At the same time we don't need CRD as in our solution all required policies are deployed via Tetragon API.

### Describe the feature you would like

We would like to be able to run Tetragon without TracingPolicy CRD, because in our scenarios it's not needed at all: all policies are deployed via API.

### Describe your proposed solution

I think one of the possible solution would be a special option both for tetragon and helm chart which will make it run in k8s cluster without access to CRD.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by aohoyd**
Fixes #1880

## Tetragon
- new flag `enable-tracing-policy-crd` was added and enabled by default

## Tetragon operator
- new flag `skip-tracing-policy-crd` was added and disabled by default

## Helm chart
- two flags above were added into configmaps and values file

### CODE REVIEW

**Comment by aohoyd** [comment]
I've synced with `main` and re-generated doc files

**Review by kkourt — COMMENTED** [review]
Thanks, this looks good to me overall. Could you please split the patch into two patches: one for the agent changes, and one for the operator changes?

**Comment by aohoyd** [comment]
> Thanks, this looks good to me. Could you please split the patch into two patches: one for the agent changes, and one for the operator changes?

Sure, done

**Comment by mtardy** [comment]
> > Thanks, this looks good to me. Could you please split the patch into two patches: one for the agent changes, and one for the operator changes?
> 
> Sure, done (I've splitted commit)
> 
> @kkourt did you mean to open separated PR?

I can't speak for Kornilios but I would say separate commits, so looking all good!

**Comment by kkourt** [comment]
> > Thanks, this looks good to me. Could you please split the patch into two patches: one for the agent changes, and one for the operator changes?
> 
> Sure, done (I've splitted commit)
> 
> @kkourt did you mean to open separated PR?

I mean splitting the commits. Thanks!

**Review by kkourt — APPROVED** [review]
LGTM, thanks!

**Comment by aohoyd** [comment]
synced fork

**Comment by lambdanis** [comment]
@aohoyd Can you rebase your branch with cilium:main instead of merging it? It makes the git history easier to read. At the moment the checkpath CI job is failing because of the merge commit (https://github.com/cilium/tetragon/actions/runs/7526335727/job/20488255210?pr=1931).

**Comment by aohoyd** [comment]
I'm not sure, but failed test looks like spontaneous error. Can anyone restart it?

**Comment by kkourt** [comment]
Tests look all good! ✅ 

@mtardy, @tpapagian, @lambdanis: do you plan to review?
Otherwise, I would suggest we merge.

**Review by tpapagian — APPROVED** [review]
Not super-familiar with this part of the codebase, but LGTM! Thanks

**Review by lambdanis — APPROVED** [review]
Small note: if all CRDs are disabled, then I believe Tetragon operator has nothing to do, but it still runs, and there is no way to disable it. Unless someone corrects me, we can update the Helm chart to allow disabling the whole operator in such cases. But this can be a follow-up, not blocking for this PR.

**Comment by lambdanis** [comment]
> Operator should be disabled in next case:
> 
> * if `tetragonOperator.podInfo.enabled` is `false` and `tetragonOperator.tracingPolicy.enabled` is `false`

Yes. One option is to introduce `tetragonOperator.enabled` Helm value, then it'll be easier to maintain I think if new CRDs are introduced. cc @michi-covalent to confirm/deny/comment.

**Review by michi-covalent — APPROVED** [review]
adding `tetragonOperator.enabled` seems reasonable if we want to be able to disable the operator altogether. we can do that as a follow-up PR ✅

**Comment by aohoyd** [comment]
I've added the new flag in #2004

**Comment by mtardy** [comment]
Failure in the CI is unrelated https://github.com/cilium/tetragon/issues/2010 and we can merge this one.

**Pull request merged**
