### PR TITLE
pkg:option: include ReadDirConfig() and remove cilium pkg option import

### PR DESCRIPTION
**Pull request by tixxdz**
Signed-off-by: Djalal Harouni <tixxdz@gmail.com>

### CODE REVIEW

**Review by tklauser — COMMENTED** [review]
It looks like the `github.com/cilium/cilium/pkg/option` package is still used in `operator/flags.go`:

https://github.com/cilium/tetragon/blob/f1a37fc2dfbf5827611ad5b9db966502ecdb0db9/operator/flags.go#L18

I think the use of that import (`option.CMDRef`) could be replaced by a local definition as well.

**Comment by jrfastab** [comment]
@tixxdz can you also take care of operator/flags.go?

**Comment by tixxdz** [comment]
> It looks like the `github.com/cilium/cilium/pkg/option` package is still used in `operator/flags.go`:
> 
> https://github.com/cilium/tetragon/blob/f1a37fc2dfbf5827611ad5b9db966502ecdb0db9/operator/flags.go#L18
> 
> I think the use of that import (`option.CMDRef`) could be replaced by a local definition as well.

Thank you @tklauser ! updated and pushed

**Review by kaworu — CHANGES_REQUESTED** [review]
CI failure is legit:

```
Module vendoring checks failed. Please run 'go mod tidy && go mod vendor && go mod verify', and submit your changes
```

Make sense to me since we're trying to get rid of vendoring `github.com/cilium/cilium/pkg/option`.

**Comment by tixxdz** [comment]
Thank you @kaworu

**Review by kaworu — APPROVED** [review]
Thanks @tixxdz nice cleanup!

**Pull request merged**
