### PR TITLE
helm: Add `tetragonOperator.enabled` flag to the chart

### PR DESCRIPTION
**Pull request by aohoyd**
A followup for https://github.com/cilium/tetragon/pull/1931#pullrequestreview-1829937445

### CODE REVIEW

**Comment by mtardy** [comment]
Thanks for taking the time to do the follow-up PR! Let me summon my colleagues who suggested this followup for review :)

**Review by michi-covalent — APPROVED** [review]
fascinating

**Comment by aohoyd** [comment]
Rebased :)

**Comment by mtardy** [comment]
Same comment as https://github.com/cilium/tetragon/pull/1931#issuecomment-1906595513 for the CI failure. This one can be merged!

**Review by lambdanis — APPROVED** [review]
looks good to me, thanks!

**Pull request merged**
