### PR TITLE
Add LICENCE

### PR DESCRIPTION
**Pull request by dgkncelik**
Signed-off-by: Doğukan ÇELİK <dogukan.celik@itu.edu.tr>

### CODE REVIEW

**Comment by dgkncelik** [comment]
Related issue #47

**Review by willfindlay — APPROVED** [review]

**Comment by willfindlay** [comment]
LGTM, thanks!

**Comment by willfindlay** [comment]
Actually @dgkncelik one more thing, do you mind squashing those commits? Thanks :)

**Comment by dgkncelik** [comment]
sorry for the inconvience :( 
just opened new pull request with correct naming
#48

**Pull request closed without merging**
