### PR TITLE
Git-ignore drop-privileges along with other binaries

### PR DESCRIPTION
**Pull request by christian-2**
As agreed in PR #2031. W/o corresponding issue, because change is minor.

### CODE REVIEW

**Review by kevsecurity — APPROVED** [review]
LGTM

**Comment by kevsecurity** [comment]
I think to fix the checkpatch test you might need to create a new branch from the up to date main and cherry-pick your first commit, and submit that. I think the second commit (the merge) is upsetting the check.

**Comment by willfindlay** [comment]
@christian-2 equivalent but perhaps easier for you: `git rebase -i origin/main` and simply drop the merge commit.

**Comment by christian-2** [comment]
@kevsecurity Should be fixed now. @willfindlay FYI what appears to have worked for me in the end was `git rebase -i ...`, `git push origin fixes-gitignore --force-with-lease` as suggested by @mtardy  in #2031.

**Review by mtardy — APPROVED** [review]
Thanks!

**Pull request merged**
