### PR TITLE
Remove unused PodInfo utility functions

### PR DESCRIPTION
**Pull request by sfc-gh-gshe**
Per discussion with John, https://cilium.slack.com/archives/C03EV7KJPJ9/p1708702221445809?thread_ts=1708626799.584219&cid=C03EV7KJPJ9

This patch removes the unused `FindPodByIP` and `FindServiceByIP` and related test.

### CODE REVIEW

**Comment by tixxdz** [comment]
Much appreciated for the contributions ;-) ! some CI tests are failing can you please check?

**Comment by sfc-gh-gshe** [comment]
> Much appreciated for the contributions ;-) ! some CI tests are failing can you please check?

Thanks for spotting this. Just fix it. Can you take another look? @tixxdz

**Comment by tixxdz** [comment]
ci failure seems unrelated tracked here: https://github.com/cilium/tetragon/issues/2156

**Review by tixxdz — APPROVED** [review]
Thank you!

**Pull request merged**
