### PR TITLE
Define syscallNames for darwin

### PR DESCRIPTION
**Pull request by michi-covalent**
Define syscallNames so that the tetra CLI compiles on Intel and ARM Mac.

Signed-off-by: Michi Mutsuzaki <michi@isovalent.com>

### CODE REVIEW

**Comment by michi-covalent** [comment]
🥺

**Review by sharlns — APPROVED** [review]

**Comment by olsajiri** [comment]
ah sry did not make it in time.. fwiw looks good ;-)

**Comment by kkourt** [comment]
Also late to the party, but I'm not  sure if that's the proper thing to do for the CLI. https://github.com/cilium/tetragon/pull/160/commits/f56c0f5e35455208f8190285d70f4f1de8bb0595, added https://github.com/cilium/tetragon/blob/27facf9a04c32e3d6f391ed824f915616e65d10b/pkg/encoder/encoder.go#L287

Which translates system call ids to names, and it uses that to figure out the arguments as well. So (at least in the above case) we would need the syscallNames of Linux (rather than dwarvin). Not sure what the best solution for this. It would probaby be better if we did this translation (id->name) on the agent.

**Comment by tklauser** [comment]
Late to the party as well. As Kornilios mentioned, these should be syscall names for Linux and the correct `$GOARCH` rather than macOS. I agree that doing the translation id->name in the agent is probably most straight forward as the `$GOARCH` is known. Ideally, we'd add something like `SyscallName` (akin to [`SignalName`](https://pkg.go.dev/golang.org/x/sys/unix#SignalName)) to the `golang.org/x/sys/unix` package which would do the translation.

**Comment by kkourt** [comment]
added issue to track this: https://github.com/cilium/tetragon/issues/539

**Pull request merged**
