### PR TITLE
tetragon: Assorted fixes

### PR DESCRIPTION
**Pull request by olsajiri**
Assorted fixes as preparation for return kprobe filtering support.
Sending self contained fixes first, so the final PR is not too big.

### CODE REVIEW

**Review by tpapagian — APPROVED** [review]
LGTM!

**Review by kkourt — COMMENTED** [review]
Thanks! Had a quick look and everything LGTM.

I do have one question based on the newly added operators.

> Unfortunately we are reaching bpf program verifier complexity limit
on 4.19 kernels, so making this change only for large programs.

What will happen if users specify the operators in 4.19?
Do we have code in place to reject these policies since they will not be applied in the datapath?

**Comment by olsajiri** [comment]
> What will happen if users specify the operators in 4.19? Do we have code in place to reject these policies since they will not be applied in the kernel side?

hm, right.. so I added that code because follow up PR is removing user space filters
for return probe and use this code in kernel instead.. I haven't though about using
LT/GT from entry probe.. that probably needs some additional checking..
is it ok in follow up PR? @kkourt

**Review by kkourt — APPROVED** [review]

**Comment by kkourt** [comment]
> > What will happen if users specify the operators in 4.19? Do we have code in place to reject these policies since they will not be applied in the kernel side?
> 
> hm, right.. so I added that code because follow up PR is removing user space filters for return probe and use this code in kernel instead.. I haven't though about using LT/GT from entry probe.. that probably needs some additional checking.. is it ok in follow up PR? @kkourt

Yap. Maybe it's worth creating an issue to track this until it's resolved. Thanks.

**Pull request merged**
