### PR TITLE
Logger is not displaying wrapped errors correctly

### PR DESCRIPTION
**Pull request by zhy76**
fix: Logger is not displaying wrapped errors correctly
Fixes: #761 
Signed-off-by: Haiyu Zuo <958474674@qq.com>

### CODE REVIEW

**Review by mtardy — CHANGES_REQUESTED** [review]
Hey, thanks. Maybe it was not clear but the goal of the issue is to see how we can fix the logger library to make it work with wrapped errors instead of just not using them.

**Comment by zhy76** [comment]
> Hey, thanks. Maybe it was not clear but the goal of the issue is to see how we can fix the logger library to make it work with wrapped errors instead of just not using them.

Thanks for your reply! 😃After my research, I found the issue is caused by logrus. The logger under tetragon uses logrus and the func of `Warnf` will finally use `Logf `which uses `fmt.Sprintf`:
image
But fmt.Sprintf does not support error-wrapping directive %w
image
Maybe we can switch to a logger library that supports the %w verb, or manually unwrap the error and log the error message.For example:
```go
if err != nil {
    if unwrappedErr := errors.Unwrap(err); unwrappedErr != nil {
        logger.GetLogger().Warnf("kprobe syscall prefix: %s", unwrappedErr.Error())
    } else {
        logger.GetLogger().Warnf("kprobe syscall prefix: %s", err.Error())
    }
}

**Comment by kkourt** [comment]
fwiw, I think this patch makes sense, even if it does not fix the above issue. How about we remove the "Fix: " part from the PR/patch and then merge it?

**Comment by zhy76** [comment]
> Thanks!
> 
> fwiw, I think this patch makes sense, even if it does not fix the above issue. How about we remove the "Fix: " part from the PR/patch and then merge it?

Do you mean only change %w to %s, or use manually unwrap the error？

**Comment by kkourt** [comment]
> > Thanks!
> > fwiw, I think this patch makes sense, even if it does not fix the above issue. How about we remove the "Fix: " part from the PR/patch and then merge it?
> 
> Thanks for reply！Did you mean only change %w to %v, or use manually unwrap the error？

Chagne `%w` to `%v`.

**Comment by zhy76** [comment]
OK，already fixed.

**Comment by zhy76** [comment]
PTAL,Thanks @kkourt

**Review by mtardy — COMMENTED** [review]
This piece of code has been moved recently 

https://github.com/cilium/tetragon/blame/ecb77f97885efebd45872177bdaf969110d02dcf/pkg/sensors/tracing/generickprobe.go#L272-L282

**Comment by jrfastab** [comment]
@zhy76 please take a look and see if the improvement is needed on the new code. Thanks!

**Comment by zhy76** [comment]
> What's the status of this PR? It looks like events have superseded it. For the future I think WithError(err) is probably the best way to include an error message in a logged event (unless anyone knows better?).

I agree with you !

**Comment by kevsecurity** [comment]
Okay, do you want to close the PR?

**Comment by zhy76** [comment]
> Okay, do you want to close the PR?

OK

**Pull request closed without merging**
