### PR TITLE
ignore .idea

### PR DESCRIPTION
**Pull request by zhy76**
ignore .idea which is for IntellJ files

### CODE REVIEW

**Comment by zhy76** [comment]
> Hi!
> 
> Thanks for the patch!
> 
> From a quick search it seems that the `.idea` folder is for IntelliJ specific files. Since we already have a `.vscode` file there, the change makes sense to me.
> 
> Could you please:
> 
> * add one sentence in the commit message saying that this is for IntellJ files
> * add a `Signed-off-by` with a real name? See: https://docs.cilium.io/en/v1.13/contributing/development/contributing_guide/#dev-coo
> 
> Thanks!

Sure!

**Comment by zhy76** [comment]
PTAL, Thanks! @kkourt

**Review by kkourt — APPROVED** [review]
Thanks!

**Comment by kkourt** [comment]
(this is a simple change, no need to run tests)

**Pull request merged**
