### PR TITLE
helm: Allow multiple installations of the Tetragon Helm chart

### LINKED ISSUE #1399: Allow Multiple Installations of the Tetragon Helm Chart
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem?

In a heterogeneous Kubernetes environment, one may want to have different Tetragon configurations (e.g., different `tetragon.extraArgs` Helm parameter for different node sizes) for different node groups. The current Helm chart can only be installed once as it creates several Kubernetes resources such as cluster roles based on "Charts.Name". 

### Describe the feature you would like

One should be able to install the Tetragon Helm chart multiple times within the same cluster. By utilizing `nodeSelectors`, `tolerations`, and `affinity`, users can establish mutually exclusive groups of Kubernetes nodes. This enables multiple deployments of Tetragon to encompass all relevant nodes in the cluster

### Describe your proposed solution

https://github.com/cilium/tetragon/pull/1400 describes a potential fix.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ashishkurmi**
fixes #1399

### CODE REVIEW

**Comment by kkourt** [comment]
Thanks!

@willfindlay or @mtardy could you please have a look at this? CC: @michi-covalent

**Comment by mtardy** [comment]
Hey @willfindlay do you want to take a look at this?

**Review by willfindlay — APPROVED** [review]
Yep this makes good sense to me

**Comment by mtardy** [comment]
I added the https://github.com/cilium/tetragon/labels/release-note%2Fminor tag, we might need a sentence for the changelog for this PR.

Sorry @ashishkurmi we delayed your PR because of unavailability and unfortunately, you now need to rebase on main. Could you do that?

**Review by willfindlay — APPROVED** [review]

**Comment by ashishkurmi** [comment]
@mtardy no worries, I have rebased my pull request, could you please review and merge it if everything looks good? I have also requested code review from @willfindlay as the earlier sign off had become stale.

**Comment by mtardy** [comment]
> @mtardy no worries, I have rebased my pull request, could you please review and merge it if everything looks good? I have also requested code review from @willfindlay as the earlier sign off had become stale.

so did you adapt in the rebase? because a new operator thingy was pushed in the helm chart right, or modified? If yes we can merge this :)

**Comment by ashishkurmi** [comment]
@mtardy yes, I updated my PR as part of the rebase. A cluster role name was renamed as part of https://github.com/cilium/tetragon/commit/84f1a3735ef1d728594127a36ca3f60e557bbe81, I have updated my PR to accomodate this change.

**Comment by mtardy** [comment]
> @mtardy yes, I updated my PR as part of the rebase. A cluster role name was renamed as part of [84f1a37](https://github.com/cilium/tetragon/commit/84f1a3735ef1d728594127a36ca3f60e557bbe81), I have updated my PR to accomodate this change.

Fantastic thanks!

**Review by mtardy — APPROVED** [review]

**Pull request merged**
